[[main]]
  identifier = "about"
  name = "about"
  url = "about"
  weight = 1

  # [[main]]
  # identifier = "posts"
  # name = "Posts"
  # url = "posts"
  # weight = 2

[[main]]
  identifier = "art"
  name = "art"
  url =  "https://www.davidlionfish.xyz/gallery/art/"
  weight = 2 

[[main]]
  identifier = "photo"
  name = "photo"
  url =  "https://www.davidlionfish.xyz/gallery/photo/"
  weight = 3   

[[main]]
  identifier = "music"
  name = "music"
  url =  "https://www.davidlionfish.xyz/posts/music/"
  weight = 4   

[[main]]
  identifier = "video"
  name = "video"
  url =  "https://www.davidlionfish.xyz/posts/video/"
  weight = 5

[[main]]
  identifier = "crypto"
  name = "crypto"
  url =  "https://www.davidlionfish.xyz/posts/crypto/"
  weight = 6  

  # [[main]]
  # identifier = "gallery"
  # name = "Gallery"
  # url = "gallery"
  # weight = 3
    
  # [[main]]
  # parent = "gallery"
  # name = "Art"
  # url = "gallery/art"

  # [[main]]
  # parent = "gallery"
  # name = "Photo"
  # url = "gallery/photo"

[[main]]
  identifier = "archive"
  name = "archive"
  url = "archive"
  weight = 7

  # [[main]]
  #  identifier = "presentation"
  #  name = "Pt"
  #  url = "presentation"
  #  weight = 5

  # [[main]]
  # identifier = "showcase"
  # name = "Showcase"
  # url = "showcase"
  # weight = 6

  # [[main]]
  # identifier = "publication"
  # name = "Pub"
  # url = "publication"
  # weight = 7